"""Tests for report_docx.build_session_report_docx (S3).

Run without conftest:
    uv run pytest apps/server/tests/test_report_docx.py -v --noconftest
"""
from __future__ import annotations

import io
from types import SimpleNamespace
from datetime import datetime, timezone

import pytest
from docx import Document

from apps.server.domain.report_docx import build_session_report_docx


# ---------------------------------------------------------------------------
# Helpers / fixtures
# ---------------------------------------------------------------------------

_DT_START = datetime(2024, 1, 15, 9, 0, 0, tzinfo=timezone.utc)
_DT_END   = datetime(2024, 1, 15, 9, 30, 0, tzinfo=timezone.utc)


def _meeting(title: str = "테스트 회의") -> SimpleNamespace:
    return SimpleNamespace(
        title=title,
        external_id="aaaabbbb-cccc-dddd-eeee-ffffgggghhhh",
        status="ended",
        started_at=_DT_START,
        ended_at=_DT_END,
        client_label=None,
    )


def _utt(
    speaker: str | None,
    text_ko: str,
    text_en: str,
    started_at: datetime = _DT_START,
    ended_at: datetime = _DT_END,
    seq: int = 0,
) -> SimpleNamespace:
    return SimpleNamespace(
        speaker=speaker,
        text_ko=text_ko,
        text_en=text_en,
        started_at=started_at,
        ended_at=ended_at,
        seq=seq,
    )


def _all_text(doc: Document) -> str:
    """Collect all paragraph text in document order."""
    return "\n".join(p.text for p in doc.paragraphs)


# ---------------------------------------------------------------------------
# Test cases
# ---------------------------------------------------------------------------


def test_valid_docx_bytes():
    """(i) Generated bytes open without error as a valid .docx."""
    b = build_session_report_docx(_meeting(), [_utt("Alice", "안녕하세요", "Hello")])
    assert isinstance(b, bytes)
    assert len(b) > 0
    doc = Document(io.BytesIO(b))
    # Must have at least one paragraph
    assert len(doc.paragraphs) > 0


def test_ko_before_en():
    """(ii) KO text appears before EN text in document paragraph order."""
    b = build_session_report_docx(
        _meeting(),
        [_utt("Alice", "안녕하세요", "Hello, how are you?")],
    )
    doc = Document(io.BytesIO(b))
    text = _all_text(doc)
    ko_pos = text.find("안녕하세요")
    en_pos = text.find("Hello, how are you?")
    assert ko_pos != -1, "KO text not found in document"
    assert en_pos != -1, "EN text not found in document"
    assert ko_pos < en_pos, "KO text must appear before EN text"


def test_none_speaker_label():
    """(iii) speaker=None produces '발화자 미상' in the document."""
    b = build_session_report_docx(
        _meeting(),
        [_utt(None, "발화 내용", "Content")],
    )
    doc = Document(io.BytesIO(b))
    text = _all_text(doc)
    assert "발화자 미상" in text


def test_consecutive_same_speaker_single_header():
    """(iv) Consecutive utterances by same speaker produce only one speaker header."""
    utts = [
        _utt("Bob", "첫 번째 발화", "First utterance", seq=0),
        _utt("Bob", "두 번째 발화", "Second utterance", seq=1),
    ]
    b = build_session_report_docx(_meeting(), utts)
    doc = Document(io.BytesIO(b))
    # Count how many headings contain "Bob"
    bob_headings = [
        p for p in doc.paragraphs
        if "Bob" in p.text and p.style.name.startswith("Heading")
    ]
    assert len(bob_headings) == 1, (
        f"Expected 1 heading for Bob, got {len(bob_headings)}: "
        f"{[p.text for p in bob_headings]}"
    )
    # Both utterances' KO text must still be present
    text = _all_text(doc)
    assert "첫 번째 발화" in text
    assert "두 번째 발화" in text


def test_empty_utterances_no_crash():
    """(v) Empty utterances list does not raise; document contains a placeholder."""
    b = build_session_report_docx(_meeting(), [])
    doc = Document(io.BytesIO(b))
    text = _all_text(doc)
    # Should have at least a placeholder and the title
    assert "테스트 회의" in text
    # Should not crash and should produce valid bytes
    assert len(b) > 100
