// === ANCHOR: CONSOLE_STYLES_START ===
import type { CSSProperties } from "react";

export const consoleStyles: Record<string, CSSProperties> = {
  page: {
    height: "100vh",
    overflow: "hidden",
    display: "grid",
    gridTemplateColumns: "var(--ys-sidebar-width) minmax(0, 1fr)",
    gridTemplateRows: "minmax(0, 1fr)",
    color: "var(--ys-text-body)",
    background: "var(--ys-bg-app)",
    fontFamily: "var(--ys-font-ui)",
  },
  sidebar: {
    overflowY: "auto",
    padding: 22,
    borderRight: "1px solid var(--ys-border-subtle)",
    background: "var(--ys-bg-sidebar)",
  },
  brand: {
    margin: "0 0 18px",
    fontSize: 13,
    fontWeight: 900,
    color: "var(--ys-accent)",
    letterSpacing: ".08em",
    textTransform: "uppercase",
  },
  version: {
    margin: "-12px 0 18px",
    fontSize: 11,
    color: "var(--ys-text-faint)",
    fontVariantNumeric: "tabular-nums",
    letterSpacing: ".04em",
  },
  nav: {
    display: "grid",
    gap: 8,
  },
  navButton: {
    width: "100%",
    padding: "12px 14px",
    borderRadius: "var(--ys-radius-control)",
    border: "1px solid var(--ys-border-subtle)",
    color: "var(--ys-text-label)",
    background: "var(--ys-surface-muted)",
    textAlign: "left",
    fontWeight: 800,
    cursor: "pointer",
  },
  navButtonActive: {
    color: "var(--ys-on-accent)",
    background: "var(--ys-accent-soft)",
    border: "1px solid var(--ys-accent-strong)",
  },
  navButtonDisabled: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  content: {
    minWidth: 0,
    height: "100%",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--ys-bg-app-gradient)",
  },
  sectionFill: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
  },
  sectionScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  panel: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: 32,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    alignItems: "flex-start",
    marginBottom: 22,
  },
  title: {
    margin: 0,
    fontSize: 40,
    letterSpacing: "-.04em",
    color: "var(--ys-text-strong)",
  },
  subtitle: {
    margin: "8px 0 0",
    color: "var(--ys-text-muted)",
    lineHeight: 1.55,
  },
  badge: {
    padding: "8px 11px",
    borderRadius: "var(--ys-radius-pill)",
    color: "var(--ys-success-text)",
    background: "var(--ys-success-bg)",
    border: "1px solid var(--ys-success-border)",
    fontSize: 12,
    fontWeight: 900,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 360px",
    gap: 18,
  },
  card: {
    padding: 22,
    borderRadius: "var(--ys-radius-card)",
    background: "var(--ys-surface-card)",
    border: "1px solid var(--ys-border)",
    boxShadow: "var(--ys-shadow-card)",
  },
  field: {
    display: "block",
    marginBottom: 14,
  },
  label: {
    display: "block",
    marginBottom: 6,
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: 900,
  },
  input: {
    boxSizing: "border-box",
    width: "100%",
    padding: "12px 13px",
    borderRadius: "var(--ys-radius-control)",
    color: "var(--ys-text-body)",
    background: "var(--ys-bg-app)",
    border: "1px solid var(--ys-border-strong)",
    outline: "none",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
  },
  action: {
    padding: "13px 15px",
    borderRadius: "var(--ys-radius-lg)",
    border: 0,
    color: "var(--ys-on-accent)",
    background: "var(--ys-accent-strong)",
    fontWeight: 950,
    cursor: "pointer",
  },
  actionDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  mutedAction: {
    padding: "13px 15px",
    borderRadius: 16,
    border: "1px solid rgba(148,163,184,.28)",
    color: "#cbd5e1",
    background: "transparent",
    fontWeight: 850,
  },
  code: {
    margin: 0,
    padding: 14,
    borderRadius: 16,
    overflow: "auto",
    color: "#bfdbfe",
    background: "#020617",
    border: "1px solid rgba(148,163,184,.18)",
    fontSize: 12,
    lineHeight: 1.65,
  },
  statusOk: {
    marginTop: 14,
    padding: 12,
    borderRadius: 14,
    color: "#bbf7d0",
    background: "rgba(22,101,52,.24)",
    border: "1px solid rgba(74,222,128,.28)",
    fontSize: 13,
    lineHeight: 1.5,
  },
  statusError: {
    marginTop: 14,
    padding: 12,
    borderRadius: 14,
    color: "#fecdd3",
    background: "rgba(159,18,57,.24)",
    border: "1px solid rgba(251,113,133,.28)",
    fontSize: 13,
    lineHeight: 1.5,
  },
  statusInfo: {
    marginTop: 10,
    padding: 12,
    borderRadius: 14,
    color: "#dbeafe",
    background: "rgba(30,64,175,.22)",
    border: "1px solid rgba(96,165,250,.26)",
    fontSize: 13,
    lineHeight: 1.5,
  },
  linkBox: {
    marginTop: 14,
    padding: 14,
    borderRadius: 16,
    color: "#e0f2fe",
    background: "rgba(14,116,144,.2)",
    border: "1px solid rgba(56,189,248,.25)",
    overflowWrap: "anywhere",
    lineHeight: 1.5,
  },
  qrPanel: {
    marginTop: 14,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: 16,
    alignItems: "center",
    padding: 14,
    borderRadius: 18,
    background: "linear-gradient(135deg, rgba(186,230,253,.14), rgba(15,23,42,.42))",
    border: "1px solid rgba(125,211,252,.24)",
  },
  qrCopy: {
    display: "grid",
    gap: 4,
    color: "#e0f2fe",
  },
  qrFrame: {
    width: 136,
    height: 136,
    display: "grid",
    placeItems: "center",
    padding: 8,
    borderRadius: 18,
    background: "#f8fafc",
    boxShadow: "0 18px 42px rgba(2,6,23,.34)",
  },
  subtitlePanel: {
    marginTop: 0,
    minHeight: 126,
    padding: 24,
    borderRadius: 24,
    background: "linear-gradient(135deg, rgba(2,6,23,.94), rgba(15,23,42,.9))",
    border: "1px solid rgba(125,211,252,.36)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,.06)",
  },
  subtitlePanelFullscreen: {
    width: "100vw",
    height: "100vh",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    minHeight: 0,
    padding: "5vh 5vw",
    borderRadius: 0,
    background: "radial-gradient(circle at 20% 0%, rgba(56,189,248,.2), transparent 30%), linear-gradient(135deg, #020617, #0f172a 56%, #172554)",
  },
  subtitleWindowPage: {
    width: "100vw",
    height: "100vh",
    margin: 0,
    overflow: "hidden",
    background: "#020617",
    color: "#f8fafc",
    fontFamily: "Aptos, 'Segoe UI', sans-serif",
  },
  subtitleHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  subtitleHeadingGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  subtitleHeaderActions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  subtitleShortcutHint: {
    color: "#94a3b8",
    fontSize: 12,
    fontWeight: 700,
  },
  subtitleMeetingTimes: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: 600,
  },
  subtitleFullscreenButton: {
    padding: "6px 10px",
    borderRadius: 999,
    color: "#dbeafe",
    background: "rgba(30,64,175,.32)",
    border: "1px solid rgba(125,211,252,.3)",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
  },
  subtitleText: {
    color: "#f8fafc",
    fontSize: 38,
    fontWeight: 900,
    lineHeight: 1.24,
    letterSpacing: "-.01em",
  },
  subtitleStack: {
    display: "grid",
    gap: 10,
  },
  subtitleContext: {
    color: "#94a3b8",
    fontSize: 24,
    fontWeight: 800,
    lineHeight: 1.32,
    letterSpacing: "-.01em",
  },
  // Fullscreen captions are LEFT-aligned on purpose: with center alignment
  // (and textWrap:balance re-splitting lines) every text update re-flowed the
  // whole block left-right — a visible "wobble" while a live line grows. Left
  // alignment makes text extend rightward/downward only, so the anchor point
  // of what you are reading never moves.
  subtitleContextFullscreen: {
    width: "86vw",
    maxWidth: "86vw",
    margin: "0 auto",
    color: "#93c5fd",
    opacity: 0.72,
    fontSize: 60,
    fontWeight: 760,
    lineHeight: 1.28,
    textAlign: "left",
    wordBreak: "keep-all",
    overflowWrap: "break-word",
  },
  subtitleTextFullscreen: {
    boxSizing: "border-box",
    width: "90vw",
    maxWidth: "90vw",
    maxHeight: "90vh",
    margin: "0 auto",
    padding: 0,
    overflow: "hidden",
    fontSize: "clamp(34px, 4.8vw, 76px)",
    fontWeight: 820,
    lineHeight: 1.24,
    letterSpacing: ".005em",
    textAlign: "left",
    wordBreak: "keep-all",
    overflowWrap: "break-word",
    textShadow: "0 4px 28px rgba(15,23,42,.52)",
  },
  // 하이브리드 모드의 미리보기 줄 — 지금 말하는 문장의 파셜이 실시간으로 자라는
  // 곳. 읽기용이 아니라 흘깃 보는 인디케이터라 일부러 작고 흐리게. 자라는
  // 텍스트가 재정렬로 출렁이지 않도록 왼쪽 정렬 고정.
  subtitlePreview: {
    color: "#7dd3fc",
    opacity: 0.62,
    fontSize: 22,
    fontWeight: 700,
    fontStyle: "italic",
    lineHeight: 1.3,
    textAlign: "left",
    wordBreak: "keep-all",
    overflowWrap: "break-word",
  },
  subtitlePreviewFullscreen: {
    width: "90vw",
    maxWidth: "90vw",
    margin: "0 auto",
    color: "#7dd3fc",
    opacity: 0.58,
    fontSize: "clamp(20px, 2.2vw, 38px)",
    fontWeight: 700,
    fontStyle: "italic",
    lineHeight: 1.3,
    textAlign: "left",
    wordBreak: "keep-all",
    overflowWrap: "break-word",
  },
  subtitleEmpty: {
    margin: "10px 0 0",
    color: "#94a3b8",
    lineHeight: 1.55,
  },
  subtitleError: {
    margin: "12px 0 0",
    color: "#fda4af",
    fontSize: 13,
  },
  subtitleMeta: {
    margin: "14px 0 0",
    color: "#64748b",
    fontSize: 12,
  },
  liveBadge: {
    padding: "6px 10px",
    borderRadius: 999,
    color: "#bbf7d0",
    background: "rgba(22,101,52,.3)",
    border: "1px solid rgba(74,222,128,.32)",
    fontSize: 12,
    fontWeight: 900,
  },
  idleBadge: {
    padding: "6px 10px",
    borderRadius: 999,
    color: "#fde68a",
    background: "rgba(146,64,14,.28)",
    border: "1px solid rgba(251,191,36,.3)",
    fontSize: 12,
    fontWeight: 900,
  },
  steps: {
    margin: 0,
    paddingLeft: 20,
    color: "#cbd5e1",
    lineHeight: 1.8,
  },
};
// === ANCHOR: CONSOLE_STYLES_END ===
