// === ANCHOR: SETTINGS_STYLES_START ===
import type { CSSProperties } from "react";

export const settingsStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    padding: 32,
    color: "#e2e8f0",
    background: "radial-gradient(circle at 12% 0%, rgba(34,211,238,.2), transparent 28%), linear-gradient(135deg, #020617, #0f172a 58%, #111827)",
    fontFamily: "Aptos, 'Segoe UI', sans-serif",
  },
  hero: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 320px",
    gap: 20,
    alignItems: "stretch",
    maxWidth: 1180,
    margin: "0 auto 22px",
  },
  eyebrow: {
    margin: 0,
    color: "#67e8f9",
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: ".1em",
    textTransform: "uppercase",
  },
  title: {
    margin: "8px 0",
    color: "#f8fafc",
    fontSize: 44,
    lineHeight: 1,
    letterSpacing: "-.05em",
  },
  subtitle: {
    maxWidth: 820,
    margin: 0,
    color: "#94a3b8",
    fontSize: 16,
    lineHeight: 1.6,
  },
  heroCard: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: 8,
    padding: 22,
    borderRadius: 24,
    color: "#ecfeff",
    background: "linear-gradient(145deg, rgba(8,47,73,.92), rgba(15,23,42,.9))",
    border: "1px solid rgba(103,232,249,.22)",
    boxShadow: "0 24px 70px rgba(8,47,73,.28)",
  },
  shell: {
    display: "grid",
    gridTemplateColumns: "280px minmax(0, 1fr)",
    gap: 18,
    maxWidth: 1180,
    margin: "0 auto",
  },
  sectionNav: {
    display: "grid",
    alignContent: "start",
    gap: 10,
  },
  sectionButton: {
    display: "grid",
    gap: 6,
    padding: 16,
    borderRadius: 18,
    border: "1px solid rgba(148,163,184,.22)",
    color: "#cbd5e1",
    background: "rgba(15,23,42,.72)",
    textAlign: "left",
    cursor: "pointer",
  },
  sectionButtonActive: {
    color: "#083344",
    background: "#a5f3fc",
    borderColor: "#67e8f9",
  },
  sectionContent: {
    minWidth: 0,
  },
  logPanel: {
    padding: 22,
    borderRadius: 26,
    background: "rgba(15,23,42,.78)",
    border: "1px solid rgba(148,163,184,.22)",
    boxShadow: "0 24px 80px rgba(0,0,0,.25)",
  },
  logHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 330px",
    gap: 18,
    alignItems: "start",
    marginBottom: 18,
  },
  sectionTitle: {
    margin: "6px 0 8px",
    color: "#f8fafc",
    fontSize: 26,
    letterSpacing: "-.03em",
  },
  helperText: {
    margin: 0,
    color: "#94a3b8",
    lineHeight: 1.55,
  },
  metricGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
  },
  metricCard: {
    display: "grid",
    gap: 6,
    padding: 12,
    borderRadius: 16,
    color: "#dbeafe",
    background: "rgba(30,64,175,.22)",
    border: "1px solid rgba(96,165,250,.24)",
    fontSize: 12,
  },
  metricDanger: {
    color: "#fecdd3",
    background: "rgba(159,18,57,.2)",
    borderColor: "rgba(251,113,133,.3)",
  },
  toolbar: {
    display: "grid",
    gridTemplateColumns: "130px 160px 110px 90px 130px",
    gap: 10,
    alignItems: "end",
    marginBottom: 10,
  },
  selectLabel: {
    display: "grid",
    gap: 5,
    color: "#cbd5e1",
    fontSize: 12,
    fontWeight: 900,
  },
  select: {
    width: "100%",
    padding: "10px 11px",
    borderRadius: 12,
    color: "#e2e8f0",
    background: "#020617",
    border: "1px solid rgba(148,163,184,.34)",
  },
  primaryButton: {
    padding: "12px 14px",
    border: 0,
    borderRadius: 14,
    color: "#042f2e",
    background: "#5eead4",
    fontWeight: 950,
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "12px 14px",
    borderRadius: 14,
    border: "1px solid rgba(148,163,184,.28)",
    color: "#dbeafe",
    background: "rgba(15,23,42,.5)",
    fontWeight: 900,
    cursor: "pointer",
  },
  disabledButton: {
    opacity: 0.45,
    cursor: "not-allowed",
  },
  saveStatus: {
    margin: "0 0 12px",
    color: "#94a3b8",
    fontSize: 12,
    overflowWrap: "anywhere",
  },
  logViewport: {
    height: "min(58vh, 560px)",
    overflow: "auto",
    padding: 12,
    borderRadius: 18,
    background: "#020617",
    border: "1px solid rgba(148,163,184,.2)",
  },
  emptyLog: {
    margin: 0,
    color: "#64748b",
    lineHeight: 1.6,
  },
  logLine: {
    display: "grid",
    gridTemplateColumns: "96px 58px 120px minmax(0, 1fr)",
    gap: 10,
    alignItems: "baseline",
    padding: "7px 8px",
    borderRadius: 10,
    fontSize: 12,
    borderLeft: "3px solid transparent",
  },
  logLineInfo: {
    color: "#cbd5e1",
    borderLeftColor: "#38bdf8",
  },
  logLineWarn: {
    color: "#fde68a",
    background: "rgba(120,53,15,.18)",
    borderLeftColor: "#f59e0b",
  },
  logLineError: {
    color: "#fecdd3",
    background: "rgba(159,18,57,.18)",
    borderLeftColor: "#fb7185",
  },
  logLineDebug: {
    color: "#94a3b8",
    borderLeftColor: "#64748b",
  },
  logTimestamp: {
    color: "#64748b",
    fontVariantNumeric: "tabular-nums",
  },
  logLevel: {
    fontWeight: 900,
    textTransform: "uppercase",
  },
  logSource: {
    color: "#67e8f9",
    fontWeight: 800,
  },
  logMessage: {
    minWidth: 0,
    color: "inherit",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    fontFamily: "'SFMono-Regular', Consolas, monospace",
  },
};
// === ANCHOR: SETTINGS_STYLES_END ===
